AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume1

  Sample SAM Template for cloud-resume1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  Putfunction:
    Type: AWS::Serverless::Function 
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: table1
      CodeUri: put_function/
      Handler: app.put_handler
      Runtime: python3.9
      Events:
        Putevent:
          Type: Api
          Properties:
            Path: /put
            Method: get

  Getfunction:
    Type: AWS::Serverless::Function 
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: table1
      CodeUri: get_function/
      Handler: app.get_handler
      Runtime: python3.9
      Events:
        Getevent:
          Type: Api
          Properties:
            Path: /get
            Method: get

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: "table1"
      KeySchema:
        - AttributeName : "counts"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "counts"
          AttributeType: "S" 

  S3bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: abininireland.click
#      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:  
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  Bucketpolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3bucket1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal: '*'
          Action: "s3:GetObject"
          Resource: !Join
            - ""
            - - "arn:aws:s3:::"
              - !Ref S3bucket1
              - /*
  Route53Record1:
    Type: AWS::Route53::RecordSetGroup
    Properties:  
      HostedZoneId: Z03065381R1I59708RRV8 
      RecordSets:
      - Name: abininireland.click
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFront1.DomainName
          
#  MyCertificate1: 
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: abininireland.click
#      ValidationMethod: DNS

  CloudFront1:
    Type:  AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
           AcmCertificateArn: "arn:aws:acm:us-east-1:086989289263:certificate/e2cfba5f-2a14-4129-92c1-0b5099a4b108"
           SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: abininireland.click.s3-website-eu-west-1.amazonaws.com
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0 
          ForwardedValues:
            QueryString: false
        Aliases: 
          - abininireland.click
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: abininireland.click.s3-website-eu-west-1.amazonaws.com
            Id: abininireland.click.s3-website-eu-west-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: http-only