name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  python: 3.9
jobs:
  base-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: test get_function
        run: |
          cd ./put_function
          pip3 install pytest pytest-mock
          python3 -m pytest tests/unit
